# Generated by Django 6.0.4 on 2026-04-30 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_comment_options_alter_task_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='created_at',
        ),
    ]
